name: e_commerce
description: A simple e-commerce app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: MonaSans
      fonts:
        - asset: assets/fonts/Mona-Sans-Regular.ttf
        - asset: assets/fonts/Mona-Sans-Medium.ttf
        - asset: assets/fonts/Mona-Sans-Bold.ttf
          
  uses-material-design: true
  assets:
      - assets/images/
      - assets/icons/
      - assets/lottie/

